version: '3.3'

services:
  nginx-1.20-alpine_azure:
    build: ./nginx-1.20-alpine_azure
  php80-fpm-alpine_azure-postgresql:
    build: ./php80-fpm-alpine_azure-postgresql
  php80-fpm-alpine_laravel-worker:
    build: ./php80-fpm-alpine_laravel-worker